config/routes.rb
MyApp::Application.routes.draw do
  
  get "users/new"
  match '/signup' , to: 'users#new'
  get "controller_test/foo"
  get "controller_test/bar"
  get "controller_test/baz"
  get "controller_test/home"
  root to: 'controller_test#home'
  match 'foo', to: 'controller_test#foo'
  match 'bar', to: 'controller_test#bar'
  match 'baz', to: 'controller_test#baz'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/controller_test_controller.rb
class ControllerTestController < ApplicationController
  def foo
  end

  def bar
  end

  def baz
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title title 
    base_title = "Ruby on Rails TEST"
    if title.empty?
      base_title
    else
      "#{base_title} #{title}"
    end
  end

end

app/helpers/controller_test_helper.rb
module ControllerTestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/controller_test/bar.html.erb
<% provide(:title, 'bar') %>
<h1><%= yield(:title)%></h1>
<p>
This is a test page
</p>

app/views/controller_test/baz.html.erb
<% provide(:title, 'baz') %>
<h1><%= yield(:title)%></h1>
<p>
This is a test page
</p>

app/views/controller_test/foo.html.erb
<h1>ControllerTest#foo</h1>
<p>Find me in app/views/controller_test/foo.html.erb</p>

app/views/controller_test/home.html.erb
<div v class="center hero-unit">
<h1>Welcome to myApp</h1>
<h2>
This is the home page for my app
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
by Michael Hartl
</small>
<nav>
<ul>
<li><%= link_to "About", foo_path %></li>
<li><%= link_to "Contact", bar_path %></li>
<li><%= link_to "Test" , baz_path %></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<%= link_to "sample app", '#', id: "logo" %>
<nav>
<ul class="nav pull-right">
<li><%= link_to "Home",root_path %></li>
<li><%= link_to "Sign in", '#'%></li>
</ul>
</nav>
</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class ="container">
    <%= yield %>
    <%= render 'layouts/footer'%>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>